name: ARCHE-Ingest

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Ingest Data into ARCHE
    runs-on: ubuntu-latest
    env:
      ARCHE_USER: ${{secrets.ARCHE_USER}}
      ARCHE_PASSWORD: ${{secrets.ARCHE_PASSWORD}}
      ARCHE: https://arche-curation.acdh-dev.oeaw.ac.at/api
      TOPCOLID: https://id.acdh.oeaw.ac.at/emt
      PROJECTID: https://id.acdh.oeaw.ac.at/emt/project

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Fetch Data
      run: ./fetch_data.sh
    - name: Process Data
      run: ./process.sh
    - name: Make RDF
      run: python make_arche_rdf.py
    - uses: actions/upload-artifact@v4
      with:
        name: arche.ttl
        path: ./to_ingest/arche.ttl
        if-no-files-found: error
        overwrite: true
    - name: Fetch WF-URL
      run: echo "RUN_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
    - name: cache AV database
      id: avdb
      uses: actions/cache@v4
      with:
        path: ~/.cvdupdate
        key: constant
    - name: refresh AV database
      run: |
        python3 -m pip install --user cvdupdate && cvd update
    - name: run virus_scan
      run: ./arche__viruscheck.sh
    - name: run filechecker
      run: ./arche__filechecker.sh
    - uses: actions/upload-artifact@v4
      with:
        name: filechecker-report
        path: ./fc_out
        if-no-files-found: error
        overwrite: true
    - name: run metadata import
      run: ./arche__ingest_md.sh
    - name: run binary_import
      run: ./arche__ingest_binaries.sh
