name: ARCHE - Filechecker and Virusscan

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      ARCHE_USER: pandorfer
      ARCHE_PASSWORD: ${{secrets.ARCHE_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setu up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install python packages
        run: pip install -r requirements.txt
      - name: Download binary data
        run: ./fetch_data.sh
      - name: process the data
        run: ./process.sh
      - name: make arche metadata
        run: python make_arche_rdf.py
      - name: check files
        run: ./arche__filechecker.sh
      - uses: actions/upload-artifact@v4
        with:
          name: filechecker-report
          path: fc_out
      - name: Run virus scan
        run: ./arche__viruscheck.sh
